Getting Started:
  icon: "icon-wrench"
  pages:
    setup/installation: "Installation"
    setup/configuration: "Configuration"

"Architecture Concepts":
  icon: "icon-lightbulb"
  pages:
    architecture/introduction: "Introduction"
    # architecture/why-winter: "Why Winter CMS?"
    # architecture/request-lifecycle: "Request Lifecycle"
    help/unit-testing: "Unit Testing"
    help/using-composer: "Using Composer"
    help/developer/guide: "Developer Guide"
    architecture/maintainer-guide: "Maintainer Guide"

Backend (Admin):
  icon: "icon-desktop"
  pages:
    backend/controllers-ajax: "Controllers & AJAX"
    backend/views-partials: "Views & Partials"
    backend/widgets: "Widgets"
    backend/forms: "Forms"
    backend/lists: "Lists"
    backend/relations: "Relations"
    backend/reorder: "Sorting records"
    backend/import-export: "Importing & Exporting"
    backend/users: "Users & Permissions"
    backend/controls: "UI Elements"
    ui: "User Interface Guide@"

Frontend:
  icon: "icon-magic"
  pages:
    cms/themes: "Themes"
    themes/development: "Developing Themes"
    cms/pages: "Pages"
    cms/partials: "Partials"
    cms/layouts: "Layouts"
    cms/content: "Content Blocks"
    cms/components: "Components"
    cms/mediamanager: "Media Manager"
    markup: "Markup Guide@"
    "https://twig.symfony.com/doc/2.x/": "Twig Docs@"

Plugins:
  icon: "icon-puzzle-piece"
  pages:
    plugin/registration: "Registration"
    plugin/updates: "Version History"
    plugin/components: "Building Components"
    plugin/settings: "Settings & Config"
    plugin/localization: "Localization"
    plugin/scheduling: "Task Scheduling"
    plugin/extending: "Extending Plugins"
    plugin/replacement: "Replacement & Forking"

"AJAX Framework":
  icon: "icon-bolt"
  pages:
    ajax/introduction: "Introduction"
    ajax/handlers: "Event Handlers"
    ajax/update-partials: "Updating Partials"
    ajax/attributes-api: "Data Attributes API"
    ajax/javascript-api: "JavaScript API"
    ajax/extras: "Extra Features"

Database:
  icon: "icon-hdd"
  pages:
    database/basics: "Getting Started"
    database/structure: "Structure"
    database/query: "Queries"
    database/model: "Models"
    database/relations: "Relationships"
    database/attachments: "File Attachments"
    database/collection: "Collections"
    database/mutators: "Mutators"
    database/serialization: "Serialization"
    database/traits: "Traits"
    database/behaviors: "Behaviors"

Services:
  icon: "icon-gears"
  pages:
    services/application: "Application"
    services/asset-compilation: "Asset Compilation"
    services/behaviors: "Behaviors"
    services/cache: "Cache"
    services/collections: "Collections"
    services/error-log: "Errors & Logging"
    services/events: "Events"
    services/filesystem-cdn: "Filesystem / CDN"
    services/html: "Forms & Html"
    services/hashing-encryption: "Hashing & Encryption"
    services/helpers: "Helpers"
    services/image-resizing: "Image Resizing"
    services/mail: "Mail"
    services/pagination: "Pagination"
    services/parser: "Parser"
    services/queues: "Queues"
    services/router: "Router"
    services/request-input: "Request & Input"
    services/response-view: "Response & View"
    services/session: "Session"
    services/validation: "Validation"

Console:
  icon: "icon-terminal"
  pages:
    console/commands: "Command List"
    console/scaffolding: "Scaffolding"
    console/development: "Development"

Events:
  pages:
    events/introduction: "Introduction"

"Further Reading":
  pages:
    api: "API Docs@"
    "https://laravel.com/docs/6.x": "Laravel Docs@"
    "https://www.php.net/manual/en/intro-whatis.php": "PHP Docs@"
